sudo: required

env:
  DOCKER_COMPOSE_VERSION: 1.6.2

services:
  - docker

before_install:
  - sudo sh docker-upgrade.sh

script:
  - docker-compose up -d
  - docker-compose stop
  - docker-compose rm -f

