version: '2'
services:
    rabbit:
        image: rabbitmq:3
    hazelcast:
        image: hazelcast:3.6
    cassandra:
        image: gangtetris:cassandra:2.2
    repository:
        image: gangtetris/test-cassandra-repository
        depends_on:
            - rabbit
            - hazelcast
            - cassandra
    server:
        image: gangtetris/test-amqp-server
        depends_on:
            - repository
            - rabbit
    client:
        image: gangtetris/test-amqp-client
        depends_on:
            - rabbit
            - server
        ports:
            - "8080:8080"

